# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://mastodon.social/@lohiarajat"
weight = 1

[social.params]
icon = "mastodon"

[[social]]
identifier = "pixelfed"
name = "Pixelfed"
url = "https://pictogram.social/i/portfolio/beigeoat"
weight = 2

[social.params]
icon = "pixelfed"


[[social]]
identifier = "lemmy"
name = "Lemmy"
url = "https://110010.win/u/beigeoat"
weight = 3

[social.params]
icon = "lemmy"

[[social]]
identifier = "mail"
name = "mail"
url = "mailto:rajat@lohia.me"
weight = 4

[social.params]
icon = "mail"